rasa_semantic_schema_redshift:
  target: analytics
  outputs:
    analytics:
      type: redshift
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASSWORD') }}"
      port: "{{ env_var('PG_PORT', 5439) | as_number }}"
      dbname: "{{ env_var('PG_DATABASE_NAME') }}"
      schema: "{{ var('dest_schema_prefix', var('source_schema_prefix')) }}"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds
      # search_path: public # optional, not recommended
      #sslmode: [optional, set the sslmode used to connect to the database (in case this parameter is set, will look for ca in ~/.postgresql/root.crt)]
      ra3: true # enables cross-database sources


rasa_semantic_schema_bigquery:
  target: analytics
  outputs:
    analytics:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('PROJECT_ID') }}"
      schema: "{{ var('dest_schema_prefix', var('source_schema_prefix')) }}"
      keyfile_json:
        type: service_account
        project_id: "{{ env_var('PROJECT_ID') }}"
        private_key: "{{ env_var('BQ_CRED_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BQ_CRED_CLIENT_EMAIL') }}"
        token_uri: "{{ env_var('BQ_CRED_TOKEN_URI') }}"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds

rasa_semantic_schema_bigquery_service_file:
  target: analytics
  outputs:
    analytics:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      schema: "{{ var('dest_schema_prefix', var('source_schema_prefix')) }}"
      keyfile: "{{ env_var('KEY_FILE_PATH') }}"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds
