
version: 2

models:
  - name: event_sequence
    columns:
      - name: _record_hash
        tests:
          - unique
          - not_null  
  - name: actions
    columns:
      - name: action_record_hash
        tests:
          - unique
          - not_null
  - name: slots
    columns:
      - name: slot_record_hash
        tests:
          - unique
          - not_null
  - name: interactions
    columns:
      - name: interaction_id
        tests:
          - unique
          - not_null
  - name: sessions
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
  - name: senders
    columns:
      - name: sender_id
        tests:
          - unique
          - not_null
  - name: users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
  - name: bot_actions
    columns:
      - name: bot_record_hash
        tests:
          - unique
          - not_null
      - name: next_user_interaction_fk
        tests:
          - relationships:
              to: ref('interactions')
              field: interaction_id
           # next_user_interaction_fk must have non null values
          - dbt_expectations.expect_column_unique_value_count_to_be_between:
              min_value: 1
  - name: user_messages
    columns:
      - name: user_message_record_hash
        tests:
          - unique
          - not_null
      - name: previous_bot_interaction_fk
        tests:
          - relationships:
              to: ref('interactions')
              field: interaction_id
           # next_user_interaction_fk must have non null values
          - dbt_expectations.expect_column_unique_value_count_to_be_between:
              min_value: 1
